version: "3.8"
services:
  client_app:
    build: .
    ports:
      - 8000:8080
    hostname: binabisa-app
    env_file: .env
    volumes:
      - ./:/usr/app
    restart: always
    depends_on:
      - inclusicareers_db
  inclusicareers_db:
    image: postgres:alpine
    ports:
      - 5436:5432
    hostname: binabisa-app-db
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
