version: "3.8"
services:
  client_app:
    build: .
    ports:
      - 8080:8080
    hostname: binabisa-app
    env_file: .env
    volumes:
      - ./:/usr/app
    restart: always
    depends_on:
      - binabisa_app_db
  binabisa_app_db:
    image: postgres:alpine
    ports:
      - 5436:5432
    hostname: binabisa-app-db
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}